name: Rust CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET: [release]
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Build
        run: cargo build --profile ${{ matrix.BUILD_TARGET }}
      
      - name: Run tests
        run: cargo test --profile ${{ matrix.BUILD_TARGET }}
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rust-app
          path: target/${{ matrix.BUILD_TARGET }}/your-app-name 